<!DOCTYPE html>
<html lang="es">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>async-await</title>
</head>

<body>
	<h1>Async-Await</h1>

	<script>
		function cuadradoPromise(value) {
			if (typeof value !== "number") {
				return Promise.reject(`El valor ingresado ${value}, no es un nÃºmero`)
			}

			return new Promise((resolve, reject) => {
				setTimeout(() => {
					resolve({
						value: value,
						result: value * value
					})
				}, 0 | Math.random() * 1000);
			})
		}

		//Funcion Declarada
		//Aqui estamos creando una funcion, la cual le pondremos la palabra async,
		//para poder hacer la funcion asyncrona.
		async function funcionAsincronaDeclarada() {
			//Aqui estamos creando un bloque 'try catch',
			//con este bloque lo que logramos es controlar la ejecucion,
			//de las funciones, y el manejo de los errores.
			
			//En el bloque 'try', vamos a poner el codigo que queremos usar,
			//el codigo que entra en este bloque no nos devuelve errores,
			//siempre que se devuelva un error ira al bloque 'catch'.
			try {
				console.log('Inicio Async Function');

				let obj = await cuadradoPromise(4);
				console.log(`Async Function 1: ${obj.value}, ${obj.result}`);

				obj = await cuadradoPromise(45);
				console.log(`Async Function 2: ${obj.value}, ${obj.result}`);

			//En el bloque 'catch', ingresara solamente el error de la ejecucion de una funcion.
			} catch (error) {
				console.log(error)

			}
		}

		funcionAsincronaDeclarada();

		//Funcion Expresada
		const funcionAsincronaExpresada = async() => {
			try {
				console.log('Inicio Async Function');

				let obj = await cuadradoPromise(4);
				console.log(`Async Function 3: ${obj.value}, ${obj.result}`);

				obj = await cuadradoPromise(65);
				console.log(`Async Function 4: ${obj.value}, ${obj.result}`);

			} catch (error) {
				console.log(error)
			}
		}
		funcionAsincronaExpresada();
	</script>
</body>

</html>